api_platform:
     # The title of the API.
    title: 'Store'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '0.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
